import React, { Component } from 'react';
import Cell from './Cell';

class GridOne extends Component {
  render() {
    return ([
      <Cell key='cell-1-1' />,
      <Cell key='cell-1-2' />,
      <Cell key='cell-1-3' />,
      <Cell key='cell-1-4' />,
      <Cell key='cell-1-5' />,
      <Cell key='cell-1-6' />,
      <Cell key='cell-1-7' />,
      <Cell key='cell-1-8' />,
      <Cell key='cell-1-9' />,
      <Cell key='cell-1-10' />,
      <Cell key='cell-1-11' />,
      <Cell key='cell-1-12' />,
      <Cell key='cell-1-13' />,
      <Cell key='cell-1-14' />,
      <Cell key='cell-1-15' />,
      <Cell key='cell-1-16' />,

      <Cell key='cell-2-1' />,
      <Cell key='cell-2-2' />,
      <Cell key='cell-2-3' />,
      <Cell key='cell-2-4' />,
      <Cell key='cell-2-5' />,
      <Cell key='cell-2-6' />,
      <Cell key='cell-2-7' />,
      <Cell key='cell-2-8' />,
      <Cell key='cell-2-9' />,
      <Cell key='cell-2-10' />,
      <Cell key='cell-2-11' />,
      <Cell key='cell-2-12' />,
      <Cell key='cell-2-13' />,
      <Cell key='cell-2-14' />,
      <Cell key='cell-2-15' />,
      <Cell key='cell-2-16' />,

      <Cell key='cell-3-1' />,
      <Cell key='cell-3-2' />,
      <Cell key='cell-3-3' />,
      <Cell key='cell-3-4' />,
      <Cell key='cell-3-5' />,
      <Cell key='cell-3-6' />,
      <Cell key='cell-3-7' />,
      <Cell key='cell-3-8' />,
      <Cell key='cell-3-9' />,
      <Cell key='cell-3-10' />,
      <Cell key='cell-3-11' />,
      <Cell key='cell-3-12' />,
      <Cell key='cell-3-13' />,
      <Cell key='cell-3-14' />,
      <Cell key='cell-3-15' />,
      <Cell key='cell-3-16' />,

      <Cell key='cell-4-1' />,
      <Cell key='cell-4-2' />,
      <Cell key='cell-4-3' />,
      <Cell key='cell-4-4' />,
      <Cell key='cell-4-5' />,
      <Cell key='cell-4-6' />,
      <Cell key='cell-4-7' />,
      <Cell key='cell-4-8' />,
      <Cell key='cell-4-9' />,
      <Cell key='cell-4-10' />,
      <Cell key='cell-4-11' />,
      <Cell key='cell-4-12' />,
      <Cell key='cell-4-13' />,
      <Cell key='cell-4-14' />,
      <Cell key='cell-4-15' />,
      <Cell key='cell-4-16' />,

      <Cell key='cell-5-1' />,
      <Cell key='cell-5-2' />,
      <Cell key='cell-5-3' />,
      <Cell key='cell-5-4' />,
      <Cell key='cell-5-5' />,
      <Cell key='cell-5-6' />,
      <Cell key='cell-5-7' />,
      <Cell key='cell-5-8' />,
      <Cell key='cell-5-9' />,
      <Cell key='cell-5-10' />,
      <Cell key='cell-5-11' />,
      <Cell key='cell-5-12' />,
      <Cell key='cell-5-13' />,
      <Cell key='cell-5-14' />,
      <Cell key='cell-5-15' />,
      <Cell key='cell-5-16' />,

      <Cell key='cell-6-1' />,
      <Cell key='cell-6-2' />,
      <Cell key='cell-6-3' />,
      <Cell key='cell-6-4' />,
      <Cell key='cell-6-5' />,
      <Cell key='cell-6-6' />,
      <Cell key='cell-6-7' />,
      <Cell key='cell-6-8' />,
      <Cell key='cell-6-9' />,
      <Cell key='cell-6-10' />,
      <Cell key='cell-6-11' />,
      <Cell key='cell-6-12' />,
      <Cell key='cell-6-13' />,
      <Cell key='cell-6-14' />,
      <Cell key='cell-6-15' />,
      <Cell key='cell-6-16' />,

      <Cell key='cell-7-1' />,
      <Cell key='cell-7-2' />,
      <Cell key='cell-7-3' />,
      <Cell key='cell-7-4' />,
      <Cell key='cell-7-5' />,
      <Cell key='cell-7-6' />,
      <Cell key='cell-7-7' />,
      <Cell key='cell-7-8' />,
      <Cell key='cell-7-9' />,
      <Cell key='cell-7-10' />,
      <Cell key='cell-7-11' />,
      <Cell key='cell-7-12' />,
      <Cell key='cell-7-13' />,
      <Cell key='cell-7-14' />,
      <Cell key='cell-7-15' />,
      <Cell key='cell-7-16' />,

      <Cell key='cell-8-1' />,
      <Cell key='cell-8-2' />,
      <Cell key='cell-8-3' />,
      <Cell key='cell-8-4' />,
      <Cell key='cell-8-5' />,
      <Cell key='cell-8-6' />,
      <Cell key='cell-8-7' />,
      <Cell key='cell-8-8' />,
      <Cell key='cell-8-9' />,
      <Cell key='cell-8-10' />,
      <Cell key='cell-8-11' />,
      <Cell key='cell-8-12' />,
      <Cell key='cell-8-13' />,
      <Cell key='cell-8-14' />,
      <Cell key='cell-8-15' />,
      <Cell key='cell-8-16' />,

      <Cell key='cell-9-1' />,
      <Cell key='cell-9-2' />,
      <Cell key='cell-9-3' />,
      <Cell key='cell-9-4' />,
      <Cell key='cell-9-5' />,
      <Cell key='cell-9-6' />,
      <Cell key='cell-9-7' />,
      <Cell key='cell-9-8' />,
      <Cell key='cell-9-9' />,
      <Cell key='cell-9-10' />,
      <Cell key='cell-9-11' />,
      <Cell key='cell-9-12' />,
      <Cell key='cell-9-13' />,
      <Cell key='cell-9-14' />,
      <Cell key='cell-9-15' />,
      <Cell key='cell-9-16' />
    ]);
  }
}

export default GridOne;